window.MONARCH_CONFIG = {
  SUPABASE_URL: "REPLACE_ME",
  SUPABASE_ANON_KEY: "REPLACE_ME",
  EDGE_BASE_URL: "REPLACE_ME",
  GOOGLE_MAPS_BROWSER_KEY: "REPLACE_ME_OPTIONAL",
  STRIPE_PUBLISHABLE_KEY: "REPLACE_ME_OPTIONAL",
  APP_ENV: "production"
};
