// Secrets à configurer dans Supabase:
// SUPABASE_URL
// SUPABASE_SERVICE_ROLE_KEY
// STRIPE_SECRET_KEY
// STRIPE_WEBHOOK_SECRET
// STRIPE_PARTNER_PRICE_ID
// STRIPE_EVENT_PRICE_ID
// OPENAI_API_KEY
// GOOGLE_MAPS_API_KEY
// RESEND_API_KEY
// EMAIL_FROM
// APP_BASE_URL
